// Base64 encoded logos for PDF generation to avoid CORS issues
export const STORE_LOGOS_BASE64: Record<string, string> = {
  // Social Media Daily logos - Blue theme (simplified SVG)
  'https://www.socialmediadaily.com': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmOGY5ZmEiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlNPQ0lBTCBNRURJQTwvdGV4dD48dGV4dCB4PSI5MCIgeT0iNDIiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNiIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkRBSUxZPC90ZXh0Pjwvc3ZnPg==',
  'https://staging.socialmediadaily.com': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmOGY5ZmEiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlNPQ0lBTCBNRURJQTwvdGV4dD48dGV4dCB4PSI5MCIgeT0iNDIiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNiIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkRBSUxZPC90ZXh0Pjwvc3ZnPg==',
  'https://www.socialmediadaily.de': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmOGY5ZmEiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlNPQ0lBTCBNRURJQTwvdGV4dD48dGV4dCB4PSI5MCIgeT0iNDIiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNiIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkRBSUxZPC90ZXh0Pjwvc3ZnPg==',
  'https://staging.socialmediadaily.de': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmOGY5ZmEiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlNPQ0lBTCBNRURJQTwvdGV4dD48dGV4dCB4PSI5MCIgeT0iNDIiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNiIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMxYTczZTgiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkRBSUxZPC90ZXh0Pjwvc3ZnPg==',
  
  // FollowerFast logos - Orange theme (simplified SVG since WebP is not supported)
  'https://www.followerfast.com': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmZmY0ZTYiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZjY5MDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkZPTExPV0VSPC90ZXh0Pjx0ZXh0IHg9IjkwIiB5PSI0MiIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmNjkwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+RkFTVDwvdGV4dD48L3N2Zz4=',
  'https://www.staging.followerfast.com': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmZmY0ZTYiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZjY5MDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkZPTExPV0VSPC90ZXh0Pjx0ZXh0IHg9IjkwIiB5PSI0MiIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmNjkwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+RkFTVDwvdGV4dD48L3N2Zz4=',
  'https://staging.followerfast.com': 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTgwIiBoZWlnaHQ9IjYwIiB2aWV3Qm94PSIwIDAgMTgwIDYwIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxyZWN0IHdpZHRoPSIxODAiIGhlaWdodD0iNjAiIGZpbGw9IiNmZmY0ZTYiLz48dGV4dCB4PSI5MCIgeT0iMjUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZjY5MDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkZPTExPV0VSPC90ZXh0Pjx0ZXh0IHg9IjkwIiB5PSI0MiIgZm9udC1mYW1pbHk9IkFyaWFsLCBzYW5zLXNlcmlmIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmNjkwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+RkFTVDwvdGV4dD48L3N2Zz4=',
};

// Get base64 logo by URL
export function getStoreLogoBase64(url: string): string | null {
  if (!url) return null;
  
  try {
    const urlObj = new URL(url);
    const baseUrl = `${urlObj.protocol}//${urlObj.hostname}`;
    return STORE_LOGOS_BASE64[baseUrl] || null;
  } catch {
    return null;
  }
}

// Get base64 logo by store name
export function getStoreLogoBase64ByName(name: string): string | null {
  if (!name) return null;
  
  const nameLower = name.toLowerCase();
  
  if (nameLower.includes('social') || nameLower.includes('media') || nameLower.includes('daily')) {
    return STORE_LOGOS_BASE64['https://www.socialmediadaily.com'];
  }
  
  if (nameLower.includes('follower') || nameLower.includes('fast')) {
    return STORE_LOGOS_BASE64['https://www.followerfast.com'];
  }
  
  return null;
}